export const products = [
    {
      id: 1,
      name: "Figura luffy ",
      category: "Hiasan ruangan",
      price: 100000,
      image: "/images/produk1.jpg",
      isCart: false,
      description: "Figura dengan kualitas premium.Cocok untuk hiasan ruangan apapun",
    },
    {
      id: 2,
      name: "Figura ASL",
      category: "Hiasan ruangan",
      price: 170000,
      image: "/images/produk2.jpg",
      isCart: false,
      description: "Figura ASL terbaru cocok untuk hiasan kamar anda",
    },
    {
      id: 3,
      name: "Figura Zoro",
      category: "Hiasan ruangan",
      price: 150000,
      image: "/images/produk3.jpg",
      isCart: false,
      description: "Penggemar Zoro wajib beli nihh,cocok untuk hiasan ruang tamu maupun kamar anda",
    },
    {
      id: 4,
      name: "Figura Nezuko",
      category: "Hiasan ruangan",
      price: 100000,
      image: "/images/produk4.jpg",
      isCart: false,
      description: "Penggemar Nezuko wajib beli nihh,cocok untuk hiasan ruang tamu maupun kamar anda",
    },
    {
      id: 5,
      name: "Figura Nagi",
      category: "Hiasan ruangan",
      price: 100000,
      image: "/images/produk5.jpg",
      isCart: false,
      description: "cocok untuk hiasan ruang tamu maupun kamar anda",
    },
    {
      id: 6,
      name: "Sepatu custom kamado tanjiro",
      category: "sepatu",
      price: 200000,
      image: "/images/produk6.jpg",
      isCart: false,
      description: "Sepatu dengan motif kekinian tetapi tidak norak. Cocok untuk pasangan outfit apa aja",
    },
    {
      id: 7,
      name: "Sepatu custom itachi uchiha",
      category: "sepatu",
      price: 200000,
      image: "/images/produk7.jpg",
      isCart: false,
      description: "Sebagai penggemar itachi wajib banget nih checkout sepatunya.Motifnya ngga norak dan modern",
    },
    {
      id: 8,
      name: "Keychain gojo",
      category: "aksesoris",
      price: 8000,
      image: "/images/produk8.jpg",
      isCart: false,
      description: "Cocok untuk gantungan kunci maupun tas",
    },
    {
      id: 9,
      name: "Keychain kimetsu no yaiba",
      category: "aksesoris",
      price: 20000,
      image: "/images/produk9.jpg",
      isCart: false,
      description: "Dengan harga 20.000 sudah mendapatkan 3 keychain.gantungan kecil yang digunakan untuk mengaitkan suatu benda kecil dengan lubang kunci.",
    },
    {
      id: 10,
      name: "earphone bluetooth akatsuki",
      category: "earphone bluetooth",
      price: 80000,
      image: "/images/produk10.jpg",
      isCart: false,
      description: "bekerja dengan gelombang radio yang didukung oleh koneksi bluetooth untuk bisa tersambung ke perangkat lain yang kamu gunakan untuk mendengarkan lagu, misalnya telepon genggam, laptop, tablet, dan lain-lain.",
    },
    {
      id: 11,
      name: "earphone bluetooth one piece",
      category: "earphone bluetooth",
      price: 80000,
      image: "/images/produk11.jpg",
      isCart: false,
      description: "bekerja dengan gelombang radio yang didukung oleh koneksi bluetooth untuk bisa tersambung ke perangkat lain yang kamu gunakan untuk mendengarkan lagu, misalnya telepon genggam, laptop, tablet, dan lain-lain.Dengan design modern",
    }
  ];